# Generated by Django 5.2 on 2025-04-22 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_emailcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='changeemailcode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
