# Generated by Django 5.2 on 2025-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_changeemailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeemailcode',
            name='step2',
            field=models.BooleanField(default=False),
        ),
    ]
