# Generated by Django 5.2 on 2025-04-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='grand_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandparentcategory', to='product.category'),
        ),
    ]
